# Generated by Django 6.0.4 on 2026-05-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=128)),
                ('token_type', models.CharField(choices=[('magic_link', 'Magic Link'), ('otp', 'OTP')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'token_type'], name='users_login_token_99d51e_idx'), models.Index(fields=['email', 'token_type'], name='users_login_email_d78c1a_idx')],
            },
        ),
    ]
