# Generated by Django 6.0.4 on 2026-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_notifications_profile_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='token_type',
            field=models.CharField(choices=[('magic_link', 'Magic Link'), ('otp', 'OTP'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
